project:
  type: website
  output-dir: docs

website:
  title: "Teaching with R"
  sidebar:
    style: "docked"
    search: true
    background: "#207282"
    logo: images/user-logo.png
    contents:
      - href: index.qmd
        text: Welcome
      - href: schedule.qmd
      - section: Slides
        contents: 
        - href: slides/01-webR-slides.qmd
         # text: "Welcome + webR"
        - href: slides/02-pedagogy.qmd
        #  text: "Curriculum and pedagogy"
        - href: slides/03-github.qmd
        #  text: "Teaching with Git and GitHub"
        - href: slides/04-teaching-materials.qmd
      - section: Demos
        contents: 
          - href: demo/demo-webr.qmd
          - href: https://st295.github.io/st295-sp25/ae-sa/github-config-post.html
            text: Set up git and R
          - href: https://github.com/useR-org-demo/my-class
            text: Demo GitHub organization
          - href: https://classroom.github.com/a/S-N-TQ7U
            text: Demo GitHub assignment
      - href: resources.qmd
        text: Resources
      - href: license.qmd
        text: License
  page-footer:
    background: "#207282"
    left: Copyright 2025, Elijah Meyer and Maria Tackett


format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: true

editor: visual

